// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sbchlgxgtxyygpxcxwbm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNiY2hsZ3hndHh5eWdweGN4d2JtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxMDgwODUsImV4cCI6MjA1NzY4NDA4NX0.1Ud2QRfzVnERRJ9ghMyqSQVu5D362Pvrrk8yFBm0-wo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);